### ISSUE TITLE
为什么我使用npm start命令报错，不能运行项目

### ISSUE THREAD

**Issue by Liang-Feifei** [iamkun/tower_game#17]

**Comment by Liang-Feifei** [comment]
之前已经运行npm install安装依赖了

**Comment by iamkun** [comment]
报错发一下

**Comment by Liang-Feifei** [comment]
TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\chengWinMiNiPC\Desktop\tower_game-master\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\Users\chengWinMiNiPC\Desktop\tower_game-master\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\Users\chengWinMiNiPC\Desktop\tower_game-master\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tower_game@1.0.0 build: `webpack --mode production --module-bind js=babel-loader`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tower_game@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chengWinMiNiPC\AppData\Roaming\npm-cache\_logs\2019-04-24T07_42_08_388Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tower_game@1.0.0 start: `npm run build && node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tower_game@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chengWinMiNiPC\AppData\Roaming\npm-cache\_logs\2019-04-24T07_42_08_444Z-debug.log

**Comment by Liang-Feifei** [comment]
> 报错发一下

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\chengWinMiNiPC\Desktop\tower_game-master\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\Users\chengWinMiNiPC\Desktop\tower_game-master\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\Users\chengWinMiNiPC\Desktop\tower_game-master\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tower_game@1.0.0 build: `webpack --mode production --module-bind js=babel-loader`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tower_game@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chengWinMiNiPC\AppData\Roaming\npm-cache\_logs\2019-04-24T07_42_08_388Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tower_game@1.0.0 start: `npm run build && node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tower_game@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chengWinMiNiPC\AppData\Roaming\npm-cache\_logs\2019-04-24T07_42_08_444Z-debug.log

**Comment by iamkun** [comment]
参考一下这里 https://github.com/plotly/dash-component-boilerplate/issues/12

**Comment by Liang-Feifei** [comment]
> 参考一下这里 [plotly/dash-component-boilerplate#12](https://github.com/plotly/dash-component-boilerplate/issues/12)

好的， 非常感谢
